config/routes.rb
Rails.application.routes.draw do
  resources :transmissions
  resources :patients

  root 'transmissions#index'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :patient
  belongs_to :infected, class_name: 'Patient'
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :transmissions
  has_many :infecteds, through: :transmissions
end

app/models/transmission.rb
class Transmission < ActiveRecord::Base
  belongs_to :patient
  belongs_to :infected, class_name: 'Patient'

  validates :patient, :infected, :location, :date, presence: true
  validates :infected, uniqueness: { scope: :patient }
  validate :repeat_transmission, :temporal_causality, on: :create

  def self.history
    Transmission.all.order(date: :asc)
  end

  private

  def repeat_transmission
    errors.add(:infected, 'infected already a carrier') if
      Transmission.where(infected: infected).count > 0
  end

  def temporal_causality
    # [TODO] cannot transmit before I am a carrier
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  def index
    @patients = Patient.all
  end

  def show
  end

  def new
    @patient = Patient.new
  end

  def edit
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to @patient, notice: 'Patient was successfully created.'
    else
      render :new
    end
  end

  def update
    if @patient.update(patient_params)
      redirect_to @patient, notice: 'Patient was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @patient.destroy
    redirect_to patients_url, notice: 'Patient was successfully destroyed.'
  end

  private

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(:name, :socsec, :hospital)
  end
end

app/controllers/transmissions_controller.rb
class TransmissionsController < ApplicationController
  before_action :set_transmission, only: [:show, :edit, :update, :destroy]

  def index
    @transmissions = Transmission.history
  end

  def show
  end

  def new
    @transmission = Transmission.new
  end

  def edit
  end

  def create
    @transmission = Transmission.new(transmission_params)
    if @transmission.save
      redirect_to @transmission, notice: 'Transmission was successfully created.'
    else
      render :new
    end
  end

  def update
    if @transmission.update(transmission_params)
      redirect_to @transmission, notice: 'Transmission was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @transmission.destroy
    redirect_to transmissions_url, notice: 'Transmission was successfully destroyed.'
  end

  private

  def set_transmission
    @transmission = Transmission.find(params[:id])
  end

  def transmission_params
    params.require(:transmission).permit(:patient_id, :infected_id, :location, :date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def all_possible_sources
    Patient.all # to expand
  end

  def all_possible_targets
    Patient.all # to expand
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
  def who_to_thank
    (tr = Transmission.where(infected: @patient).first) ? tr.patient.name : 'Patient Zero'
  end
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :patient_id %><br>
    <%= f.text_field :patient_id %>
  </div>
  <div class="field">
    <%= f.label :patient_id %><br>
    <%= f.text_field :patient_id %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contagion</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :socsec %><br>
    <%= f.text_field :socsec %>
  </div>
  <div class="field">
    <%= f.label :hospital %><br>
    <%= f.text_field :hospital %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1>Patients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Socsec</th>
      <th>Hospital</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= patient.socsec %></td>
        <td><%= patient.hospital %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>
|
<%= link_to 'Transmission History', transmissions_path %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>Socsec:</strong>
  <%= @patient.socsec %>
</p>

<p>
  <strong>Hospital:</strong>
  <%= @patient.hospital %>
</p>

<p>
  <strong>Infected By:</strong>
  <%= who_to_thank %>
</p>

<p>
  <% unless @patient.infecteds.blank? %>
    <strong>Infected the following:</strong>
    <table>
      <thead></thead>
      <tbody>
        <% @patient.infecteds.each do |inf| %>
        <% t = @patient.transmissions.find_by(infected: inf) %>
          <tr>
            <td><%= inf.name %></td>
            <td>On <%= t.date %></td>
            <td>in <%= t.location %></td>
            <td><%= link_to "follow infectious vector", inf %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back to All Patients', patients_path %>

app/views/transmissions/_form.html.erb
<%= form_for(@transmission) do |f| %>
  <% if @transmission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transmission.errors.count, "error") %> prohibited this transmission from being saved:</h2>

      <ul>
      <% @transmission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :patient_id %><br>
    <%= f.collection_select(:patient_id, all_possible_sources, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :infected_id %><br>
    <%= f.collection_select(:infected_id, all_possible_targets, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_field :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transmissions/edit.html.erb
<h1>Editing transmission</h1>

<%= render 'form' %>

<%= link_to 'Show', @transmission %> |
<%= link_to 'Back', transmissions_path %>

app/views/transmissions/index.html.erb
<h1>Transmission Events</h1>

<table>
  <thead>
    <tr>
      <th>Source</th>
      <th>Target</th>
      <th>Location</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transmissions.each do |transmission| %>
      <tr>
        <td><%= transmission.patient.name %></td>
        <td><%= transmission.infected.name %></td>
        <td><%= transmission.location %></td>
        <td><%= transmission.date %></td>
        <td><%= link_to 'Show', transmission %></td>
        <td><%= link_to 'Edit', edit_transmission_path(transmission) %></td>
        <td><%= link_to 'Destroy', transmission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transmission', new_transmission_path %>
|
<%= link_to 'List of Patients', patients_path %>

app/views/transmissions/new.html.erb
<h1>New Transmission Event</h1>

<%= render 'form' %>

<%= link_to 'Back', transmissions_path %>

app/views/transmissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vector Patient:</strong>
  <%= @transmission.patient.name %>
</p>

<p>
  <strong>Infected Patient:</strong>
  <%= @transmission.infected.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @transmission.location %>
</p>

<p>
  <strong>Date:</strong>
  <%= @transmission.date %>
</p>

<%= link_to 'Edit', edit_transmission_path(@transmission) %> |
<%= link_to 'Back', transmissions_path %>